name: py38-nn-art-epoch-assignment
channels:
  - defaults
dependencies:
  - pandas
  - python=3.8
  - selenium
  - flask
  - matplotlib
  - regex
  - tensorflow
  - opencv
  - requests
  - keras
  - jupyter
  - scikit-learn